use sea_orm_migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait::async_trait]
impl MigrationTrait for Migration {
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        // ── users ─────────────────────────────────────────────────────────────
        manager
            .create_table(
                Table::create()
                    .table(Users::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Users::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Users::Email)
                            .string()
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(Users::Username)
                            .string()
                            .not_null()
                            .unique_key(),
                    )
                    .col(ColumnDef::new(Users::PasswordHash).string().not_null())
                    .col(
                        ColumnDef::new(Users::Role)
                            .string()
                            .not_null()
                            .default("user"),
                    )
                    .col(
                        ColumnDef::new(Users::IsActive)
                            .boolean()
                            .not_null()
                            .default(true),
                    )
                    .col(
                        ColumnDef::new(Users::EmailVerified)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(ColumnDef::new(Users::TotpSecret).string().null())
                    .col(
                        ColumnDef::new(Users::TotpEnabled)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(Users::FailedLoginAttempts)
                            .integer()
                            .not_null()
                            .default(0),
                    )
                    .col(ColumnDef::new(Users::LockedUntil).timestamp().null())
                    .col(ColumnDef::new(Users::CreatedAt).timestamp().not_null())
                    .col(ColumnDef::new(Users::UpdatedAt).timestamp().not_null())
                    .to_owned(),
            )
            .await?;

        // ── refresh_tokens ────────────────────────────────────────────────────
        manager
            .create_table(
                Table::create()
                    .table(RefreshTokens::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(RefreshTokens::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(RefreshTokens::UserId).integer().not_null())
                    .col(
                        ColumnDef::new(RefreshTokens::TokenHash)
                            .string()
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(RefreshTokens::ExpiresAt)
                            .timestamp()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RefreshTokens::Revoked)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(ColumnDef::new(RefreshTokens::IpAddress).string().null())
                    .col(ColumnDef::new(RefreshTokens::UserAgent).string().null())
                    .col(
                        ColumnDef::new(RefreshTokens::CreatedAt)
                            .timestamp()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        // ── sessions ──────────────────────────────────────────────────────────
        manager
            .create_table(
                Table::create()
                    .table(Sessions::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Sessions::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(Sessions::UserId).integer().not_null())
                    .col(ColumnDef::new(Sessions::TokenHash).string().not_null())
                    .col(ColumnDef::new(Sessions::ExpiresAt).timestamp().not_null())
                    .col(
                        ColumnDef::new(Sessions::Revoked)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(ColumnDef::new(Sessions::IpAddress).string().null())
                    .col(ColumnDef::new(Sessions::UserAgent).string().null())
                    .col(ColumnDef::new(Sessions::CreatedAt).timestamp().not_null())
                    .to_owned(),
            )
            .await?;

        // ── security_tokens ───────────────────────────────────────────────────
        manager
            .create_table(
                Table::create()
                    .table(SecurityTokens::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(SecurityTokens::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(SecurityTokens::UserId).integer().not_null())
                    .col(
                        ColumnDef::new(SecurityTokens::TokenHash)
                            .string()
                            .not_null()
                            .unique_key(),
                    )
                    .col(
                        ColumnDef::new(SecurityTokens::TokenType)
                            .string()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(SecurityTokens::ExpiresAt)
                            .timestamp()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(SecurityTokens::Used)
                            .boolean()
                            .not_null()
                            .default(false),
                    )
                    .col(
                        ColumnDef::new(SecurityTokens::CreatedAt)
                            .timestamp()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        // ── login_events ──────────────────────────────────────────────────────
        manager
            .create_table(
                Table::create()
                    .table(LoginEvents::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(LoginEvents::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(LoginEvents::UserId).integer().null())
                    .col(ColumnDef::new(LoginEvents::Email).string().not_null())
                    .col(ColumnDef::new(LoginEvents::Success).boolean().not_null())
                    .col(ColumnDef::new(LoginEvents::FailureReason).string().null())
                    .col(ColumnDef::new(LoginEvents::IpAddress).string().null())
                    .col(ColumnDef::new(LoginEvents::UserAgent).string().null())
                    .col(
                        ColumnDef::new(LoginEvents::CreatedAt)
                            .timestamp()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        // ── permissions ───────────────────────────────────────────────────────
        manager
            .create_table(
                Table::create()
                    .table(Permissions::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(Permissions::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(
                        ColumnDef::new(Permissions::Codename)
                            .string()
                            .not_null()
                            .unique_key(),
                    )
                    .col(ColumnDef::new(Permissions::Name).string().not_null())
                    .col(ColumnDef::new(Permissions::Description).string().null())
                    .col(
                        ColumnDef::new(Permissions::CreatedAt)
                            .timestamp()
                            .not_null(),
                    )
                    .to_owned(),
            )
            .await?;

        // ── role_permissions ──────────────────────────────────────────────────
        manager
            .create_table(
                Table::create()
                    .table(RolePermissions::Table)
                    .if_not_exists()
                    .col(
                        ColumnDef::new(RolePermissions::Id)
                            .integer()
                            .not_null()
                            .auto_increment()
                            .primary_key(),
                    )
                    .col(ColumnDef::new(RolePermissions::Role).string().not_null())
                    .col(
                        ColumnDef::new(RolePermissions::PermissionId)
                            .integer()
                            .not_null(),
                    )
                    .col(
                        ColumnDef::new(RolePermissions::CreatedAt)
                            .timestamp()
                            .not_null(),
                    )
                    .foreign_key(
                        ForeignKey::create()
                            .name("fk_role_permissions_permission")
                            .from(RolePermissions::Table, RolePermissions::PermissionId)
                            .to(Permissions::Table, Permissions::Id)
                            .on_delete(ForeignKeyAction::Cascade),
                    )
                    .to_owned(),
            )
            .await?;

        // ── unique index on (role, permission_id) ─────────────────────────────
        manager
            .create_index(
                Index::create()
                    .name("idx_role_permissions_unique")
                    .table(RolePermissions::Table)
                    .col(RolePermissions::Role)
                    .col(RolePermissions::PermissionId)
                    .unique()
                    .to_owned(),
            )
            .await?;

        Ok(())
    }

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {
        manager
            .drop_table(
                Table::drop()
                    .table(RolePermissions::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(Permissions::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(LoginEvents::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(SecurityTokens::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(Sessions::Table).if_exists().to_owned())
            .await?;
        manager
            .drop_table(
                Table::drop()
                    .table(RefreshTokens::Table)
                    .if_exists()
                    .to_owned(),
            )
            .await?;
        manager
            .drop_table(Table::drop().table(Users::Table).if_exists().to_owned())
            .await?;
        Ok(())
    }
}

// ── Iden enums ────────────────────────────────────────────────────────────────

#[derive(Iden)]
enum Users {
    Table,
    Id,
    Email,
    Username,
    PasswordHash,
    Role,
    IsActive,
    EmailVerified,
    TotpSecret,
    TotpEnabled,
    FailedLoginAttempts,
    LockedUntil,
    CreatedAt,
    UpdatedAt,
}

#[derive(Iden)]
enum RefreshTokens {
    Table,
    Id,
    UserId,
    TokenHash,
    ExpiresAt,
    Revoked,
    IpAddress,
    UserAgent,
    CreatedAt,
}

#[derive(Iden)]
enum Sessions {
    Table,
    Id,
    UserId,
    TokenHash,
    ExpiresAt,
    Revoked,
    IpAddress,
    UserAgent,
    CreatedAt,
}

#[derive(Iden)]
enum SecurityTokens {
    Table,
    Id,
    UserId,
    TokenHash,
    TokenType,
    ExpiresAt,
    Used,
    CreatedAt,
}

#[derive(Iden)]
enum LoginEvents {
    Table,
    Id,
    UserId,
    Email,
    Success,
    FailureReason,
    IpAddress,
    UserAgent,
    CreatedAt,
}

#[derive(Iden)]
enum Permissions {
    Table,
    Id,
    Codename,
    Name,
    Description,
    CreatedAt,
}

#[derive(Iden)]
enum RolePermissions {
    Table,
    Id,
    Role,
    PermissionId,
    CreatedAt,
}
